server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmd2022emp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20021229Fu

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.bmd.springbootemp.entity
    mapper-locations: classpath:mappers/*.xml